import Head from "next/head";
import Image from "next/image";
import logo from "./../../public/donut.png";
import Main from "./main";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  let [initialLoad, setInitialLoad] = useState(true);

  /*useEffect(() => {
    fetch("/api/hello/", {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    })
      .then((res) => res.json())
      .then((data) => {
        setMessage(data.message);
        setLoading(false);
      });
  }, []);*/

  if (initialLoad) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className={styles.App}>
            <header className={styles.AppHeader}>
              <Image src={logo} alt="logo" className={styles.AppLogo} />
              <p>Welcome to AI Shopping Helper.</p>
              <button
                className={styles.AppLinkBase + " " + styles.AppLink4}
                onClick={() => setInitialLoad(false)}
              >
                Start the app
              </button>
            </header>
          </div>
        </main>
      </>
    );
  } else {
    return (
      <>
        <Main />
      </>
    );
  }
}
